name: Continuous Integration
on: [push]
jobs:
  specs:
    name: specs
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
    steps:
    - uses: zendesk/checkout@v3
    - uses: zendesk/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run specs on Ruby ${{ matrix.ruby }}
      run: bundle exec rake spec
  linters:
    name: linters
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task:
          - brakeman
          - flay
          - rubocop
    steps:
    - uses: zendesk/checkout@v3
    - uses: zendesk/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Run ${{ matrix.task }}
      run: bundle exec rake ${{ matrix.task }}
