name: Security
on: [push]
jobs:
  main:
    name: bundle-audit
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
    - uses: zendesk/checkout@v3
    - uses: zendesk/setup-ruby@v1
      with:
        ruby-version: 2.7.8

    - name: Gem install
      run: |
        set -eu -o pipefail
        gem install bundler-audit

    - run: |
        set -eu -o pipefail

        IGNORED="CVE-2020-26247 GHSA-7rrm-v45f-jp64"

        if [ -n "$IGNORED" ]; then
          echo "::warning:: Ignored vulnerabilities: $IGNORED"
        fi

        bundle-audit check --update --gemfile-lock Gemfile.lock --ignore $IGNORED
