name: Security
on: [push]
permissions:
  contents: read
jobs:
  main:
    name: bundle-audit
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
    - uses: actions/checkout@v7
    - uses: ruby/setup-ruby@v1

    - name: Gem install
      run: |
        set -eu -o pipefail
        gem install bundler-audit

    - run: |
        set -eu -o pipefail

        IGNORED=""

        if [ -n "$IGNORED" ]; then
          echo "::warning:: Ignored vulnerabilities: $IGNORED"
          bundle-audit check --update --gemfile-lock Gemfile.lock --ignore $IGNORED
        else
          bundle-audit check --update --gemfile-lock Gemfile.lock
        fi
