name: Security
on: [push]
permissions:
  contents: read
jobs:
  main:
    name: bundle-audit
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
    - uses: zendesk/checkout@v3
    - uses: zendesk/setup-ruby@v1
      with:
        ruby-version: 3.3.7

    - name: Gem install
      run: |
        set -eu -o pipefail
        gem install bundler-audit

    - run: |
        set -eu -o pipefail

        IGNORED=""

        if [ -n "$IGNORED" ]; then
          echo "::warning:: Ignored vulnerabilities: $IGNORED"
          bundle-audit check --update --gemfile-lock Gemfile.lock --ignore $IGNORED
        else
          bundle-audit check --update --gemfile-lock Gemfile.lock
        fi
